Weather v1
Shaqri/Weather_app pull request #1
Opened 2021-01-17 00:03 UTC by Shaqri

# Hi there!

## This weather app information was taken from openWeather  Api. I add the following features for this app:
- Search bar (Were user can search for any location in space-separated city/state/country format)
- Display info about the given location.
- All possible errors for search handled.

>> All features linters fixed.

2021-01-17 01:11 UTC, elmejdki requested changes
# status: require changes :recycle: 

Hi @Shaqri your app looks good on the screenshot but I couldn't run it please check the comments below:
::point_down: :point_down: :point_down: :point_down: point_down:

## Required Changes :red_circle: 
 
- [x] Add instructions on how to run the app, and different available scripts.

- [x] Add a live demo link.

- [x] Fix the linter errors
![image](https://user-images.githubusercontent.com/34653764/104828184-c5995180-5866-11eb-9bd9-c3be013c5eb1.png)

- [x] you are missing a necessary config file in your project that's because you added it to .gitignore, I think the config file has an API_secret or something that's not how to hide your API secrets contact me if you want to learn more about it. 
![image](https://user-images.githubusercontent.com/34653764/104828270-ced6ee00-5867-11eb-9eab-a6fc395b5494.png)

- [ ] In stall webpack-dev-server package and add this script to your package.json
`"start": "webpack-dev-server --mode development --open"`

- [ ] README file contains all that's needed for running the app with the API(s) it consumes. It should have instructions about where and how to generate any necessary keys, credentials, how to set, store, and generate them(if necessary).

### Please make all the required changes before you submit for another code review.
## Happy Coding :tophat: 
_Feel free to contact me on slack if you have any questions or need help._
## _Zakariae El Mejdki_

2021-01-19 00:07 UTC, christianotieno requested changes
## Changes Required ♻️  
Hello @Shaqri 👋 
Congratulations on the hard work done in this project. 👏 
Before these changes get approved let's ensure the project has met all the needed requirements. 
We should always aim for our projects to be `plug & play` as much as possible. See my suggestion below 👇 

### Happy coding 💻 
#### Christian Otieno (CR)

2021-01-19 00:07 UTC, christianotieno commented on README.md
> +- Explore the weather from all differents parts of the world you can imagine.
## Required change
- Add additional instructions on how to;
- [ ] Install dependencies
- [ ] Setup users's  API keys in the environment 
- [ ] Run the application.

2021-01-19 04:36 UTC, BrittanyBlake approved these changes
### Status: Approved ✅ 
****
### Hi Team! 👋 
### Great job implementing the requested changes!! 🎖️ It's a 👍 from me! Go ahead and merge this pull request and keep up the good work 😄
****


 Good Luck and Happy Coding! 🍀 👩🏾‍💻

2021-01-19 06:24 UTC, merged